# Generated by Django 4.0.1 on 2022-01-16 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='date_shipping',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='direction',
            field=models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], default='OUT', max_length=3),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_address',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.shipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
