# Generated by Django 4.0.1 on 2022-01-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_shipment_company_shipment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipmentitem_item', to='inventory.item'),
        ),
    ]
