# Generated by Django 4.0.1 on 2022-01-18 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='date_shipped',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
