# Generated by Django 4.0.1 on 2022-01-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_shipment_date_shipped_shipment_is_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='date_shipping',
            new_name='date_promised',
        ),
    ]
