# Generated by Django 4.0.1 on 2022-01-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_date_shipping_shipment_date_promised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date_shipped',
            field=models.DateTimeField(null=True),
        ),
    ]
