# Generated by Django 4.0.1 on 2022-01-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_shipment_date_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
