# Generated by Django 4.0.1 on 2022-01-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_shipmentitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_iteminventory', to='inventory.item'),
        ),
    ]
