# Generated by Django 4.0.1 on 2022-01-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_shipmentitem_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='is_shipped',
        ),
    ]
