# Generated by Django 4.0.1 on 2022-01-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_shipmentitem_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
