# Generated by Django 4.0.1 on 2022-01-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_item_quantity_item_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
