# Generated by Django 4.0.1 on 2022-01-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
