# Generated by Django 4.0.1 on 2022-01-20 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_item_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.shipment'),
        ),
    ]
